version: "3.8"
services:
  advent-of-code-2022:
    image: "postgres:15.1-alpine"
    command: postgres -c max_connections=500
    ports:
      - "55432:5432"
    environment:
      - "POSTGRES_USER=aoc2022"
      - "POSTGRES_PASSWORD=aoc2022"
      - "POSTGRES_DB=aoc2022db"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
    